all:
	$(MAKE) -f testSuiteMakefileTest.mak $@
	$(MAKE) -f skipTest.mak $@
	$(MAKE) -f testSummaryTest.mak $@
	$(MAKE) -f verCmdTest.mak $@
	$(MAKE) -f castUtilTest.mak $@
	$(MAKE) -f addTestSuiteCmdTest.mak $@
	$(MAKE) -f aboutCmdTest.mak $@
	$(MAKE) -f usageCmdTest.mak $@
	$(MAKE) -f castCmdTest.mak $@
	$(MAKE) -f cmdFactoryTest.mak $@
	$(MAKE) -f cmdLineTest.mak $@
	$(MAKE) -f castCmdExecTest.mak $@

%:
	$(MAKE) -f testSuiteMakefileTest.mak $@
	$(MAKE) -f skipTest.mak $@
	$(MAKE) -f testSummaryTest.mak $@
	$(MAKE) -f verCmdTest.mak $@
	$(MAKE) -f castUtilTest.mak $@
	$(MAKE) -f addTestSuiteCmdTest.mak $@
	$(MAKE) -f aboutCmdTest.mak $@
	$(MAKE) -f usageCmdTest.mak $@
	$(MAKE) -f castCmdTest.mak $@
	$(MAKE) -f cmdFactoryTest.mak $@
	$(MAKE) -f cmdLineTest.mak $@
	$(MAKE) -f castCmdExecTest.mak $@

